=== nablarch/nablarch-biz-sample-all/nablarch-messaging-simulator/src/test/resources/component-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://tis.co.jp/nablarch/component-configuration"
    elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://tis.co.jp/nablarch/component-configuration">

    <element name="component-configuration">
        <annotation>
            <documentation>コンポーネント設定のルート要素。</documentation>
        </annotation>
        <complexType>
            <choice maxOccurs="unbounded" minOccurs="1">
                <element name="import" type="tns:Import" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>他の設定ファイルのインポートを設定する。
コンテナは設定に従い再帰的に他の設定ファイルの読み込みを行なう。</documentation>
                    </annotation>
                </element>
                <element name="config-file"
                    type="tns:ConfigFile" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>プロパティファイルの読み込みを設定する。
コンテナは設定に従い再帰的にプロパティファイルの読み込みを行なう。

プロパティファイルに記述された文字列は、XMLファイル内で"${propName}"のように参照できる。</documentation>
                    </annotation>
                </element>
                <element name="component" type="tns:Component" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>コンポーネントを設定する。
コンテナはこの設定に従い、コンポーネントの生成とインジェクションを行いコンテナ内に登録する。</documentation>
                    </annotation>
                </element>
                <element name="list" type="tns:List" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>Listをコンポーネントとして設定する。
コンテナはこの設定に従い、Listインタフェースを実装したインスタンスを生成、構築しコンポーネントとしてコンテナ内に登録する。</documentation>
                    </annotation>
                </element>
                <element name="map" type="tns:Map" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>Mapをコンポーネントとして設定する。
コンテナはこの設定に従い、Mapインタフェースを実装したインスタンスを生成、構築しコンポーネントとしてコンテナ内に登録する。</documentation>
                    </annotation>
                </element>
            </choice>
        </complexType>
    </element>

    <complexType name="Component">
        <annotation>
            <documentation>コンポーネント定義を行う型。</documentation>
        </annotation>
        <sequence>
            <element name="property" type="tns:Property"
                maxOccurs="unbounded" minOccurs="0">
                <annotation>
                    <documentation>コンポーネントのプロパティを設定する。
コンテナはこの要素に設定された値に従い、コンポーネントにプロパティを設定する。</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="name" type="string">
            <annotation>
                <documentation>コンポーネントの名称を設定する。
コンテナはこの属性で設定した名称でこのコンポーネントを登録する。


</documentation>
            </annotation></attribute>
        <attribute name="class" type="string" use="required">
            <annotation>
                <documentation>コンポーネントのクラス名を設定する。
コンテナはこの属性に設定したクラス名を利用してコンポーネントを作成する。
</documentation>
            </annotation></attribute>
        <attribute name="autowireType" type="tns:AutowireType" default="ByType">
            <annotation>
                <documentation>コンポーネントに対して適用する自動インジェクションのタイプを設定する。
コンテナはこの設定を参照して自動インジェクションを行う。

省略した場合、ByTypeを選択した場合と同様の動作となる。</documentation>
            </annotation></attribute>
    </complexType>

    <complexType name="Property">
        <annotation>
            <documentation>コンポーネントにプロパティを設定する際に利用する型。</documentation>
        </annotation>
        <choice >
            <element name="component" type="tns:Component" maxOccurs="1"
                minOccurs="0">
                <annotation>
                    <documentation>プロパティにセットするコンポーネントを設定する。
コンテナはこの要素のコンポーネントを生成し、プロパティにセットする。

この要素にname属性を設定した場合、コンポーネントの名称は上位に位置するコンポーネントの名称の後に「.」を付けてname属性に指定した文字列を結合したものとなる。</documentation>
                </annotation>
            </element>
            <element name="list" type="tns:List" maxOccurs="1"
                minOccurs="0">
                <annotation>
                    <documentation>プロパティにセットするListを設定する。
コンテナはこの要素で定義したListをコンポーネントとして生成し、プロパティにセットする。

この要素にname属性を設定した場合、コンポーネントの名称は上位に位置するコンポーネントの名称の後に「.」を付けてname属性に指定した文字列を結合したものとなる。</documentation>
                </annotation>
            </element>
            <element name="map" type="tns:Map" maxOccurs="1" minOccurs="0">
                <annotation>
                    <documentation>プロパティにセットするMapを設定する。
コンテナはこの要素で定義したMapをコンポーネントとして生成し、プロパティにセットする。

この要素にname属性を設定した場合、コンポーネントの名称は上位に位置するコンポーネントの名称の後に「.」を付けてname属性に指定した文字列を結合したものとなる。</documentation>
                </annotation></element>
        </choice>
        <attribute name="name" type="string" use="required">
            <annotation>
                <documentation>コンポーネントのプロパティ名を設定する。
コンテナはこの設定値に合致するセッタを検索し、プロパティを設定する。</documentation>
            </annotation></attribute>
        <attribute name="value" type="string">
            <annotation>
                <documentation>プロパティにセットする値を設定する。
コンテナはここに設定した文字列を、プロパティの型に併せて変換し、コンポーネントにセットする。

この属性はプロパティの型が下記いずれかの型の場合のみ設定できる。
 * int
 * long
 * boolean
 * java.lang.String
 * java.lang.Integer
 * java.lang.Long
 * java.lang.Boolean
 * java.lang.String[]
</documentation>
            </annotation></attribute>
        <attribute name="ref" type="string">
            <annotation>
                <documentation>プロパティにセットする他のコンポーネントの名称を設定する。
コンテナはこの属性に設定された文字列に合致するコンポーネントをプロパティにセットする。</documentation>
            </annotation></attribute>
    </complexType>


    <complexType name="List">
        <annotation>
            <documentation>Listをコンポーネントとして設定する際に利用する型。</documentation>
        </annotation>
        <choice maxOccurs="unbounded" minOccurs="1">
            <element name="component" type="tns:Component"
                maxOccurs="unbounded" minOccurs="0">
                <annotation>
                    <documentation>
                        Listに含まれるコンポーネントを設定する。
                        コンテナはこの要素に従いコンポーネントを生成し、上位の要素で設定したlistに追加する。
                    </documentation>
                </annotation>
            </element>
            <element name="value" type="string" minOccurs="0"
                maxOccurs="unbounded">
                <annotation>
                    <documentation>
                        Listに含まれる文字列を設定する。
                        コンテナはこの設定に従い、この要素の文字列を上位の要素で設定したlistに追加する。
                    </documentation>
                </annotation>
            </element>
            <element name="component-ref" type="tns:ComponentRef" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>Listに含まれる別定義したコンポーネントを設定する。
コンテナはこの設定に従い、この要素で参照されるコンポーネントをlistに追加する。
                    </documentation>
                </annotation></element>
        </choice>
        <attribute name="name" type="string">
            <annotation>
                <documentation>Listのコンポーネント名を設定する。
コンテナはこの属性で設定した名称でこのListをコンポーネントとして登録する。
</documentation>
            </annotation></attribute>
    </complexType>

    <complexType name="Map">
        <annotation>
            <documentation>Mapをコンポーネントとして設定する際に利用する型。</documentation>
        </annotation>
        <sequence>
            <element name="entry" type="tns:Entry" maxOccurs="unbounded" minOccurs="0">
                <annotation>
                    <documentation>Mapのエントリを設定する。
コンテナはこの要素の設定に従い、Mapにエントリを追加する。</documentation>
                </annotation></element>
        </sequence>
        <attribute name="name" type="string">
            <annotation>
                <documentation>Mpaのコンポーネント名を設定する。
コンテナはこの属性で設定した名称でこのMapをコンポーネントとして登録する。
</documentation>
            </annotation></attribute>
    </complexType>
    
    <complexType name="Entry">
        <annotation>
            <documentation>Mapのエントリを設定する型。</documentation>
        </annotation>
        <sequence>
            <element name="key-component" type="tns:Component"
                maxOccurs="1" minOccurs="0">
                <annotation>
                    <documentation>エントリのキーとなるコンポーネントを設定する。
コンテナはこの要素で設定されたコンポーネントをキーとするエントリを上位の要素で設定したmapに追加する。
</documentation>
                </annotation>
            </element>
            <element name="value-component" type="tns:Component" maxOccurs="1" minOccurs="0">
                <annotation>
                    <documentation>エントリの値となるコンポーネントを設定する。
コンテナはこの要素で設定されたコンポーネントを値とするエントリを上位の要素で設定したmapに追加する。</documentation>
                </annotation></element>
        </sequence>
        <attribute name="key" type="string">
            <annotation>
                <documentation>エントリのキーを設定する。
コンテナはこの属性で設定された文字列をキーとするエントリを上位の要素で設定したmapに追加する。</documentation>
            </annotation></attribute>
        <attribute name="key-name" type="string">
            <annotation>
                <documentation>エントリのキーとなるコンポーネント名を設定する。
コンテナはこの属性で設定された名称に合致するコンポーネントをキーとするエントリを上位の要素で設定したmapに追加する。

</documentation>
            </annotation></attribute>
        <attribute name="value" type="string">
            <annotation>
                <documentation>エントリの値を設定する。
コンテナはこの属性で設定された文字列を値とするエントリを上位の要素で設定したmapに追加する。</documentation>
            </annotation></attribute>
        <attribute name="value-name" type="string">
            <annotation>
                <documentation>エントリの値となるコンポーネントを設定する。
コンテナはこの属性で設定された名称に合致するコンポーネントを値とするエントリを上位の要素で設定したmapに追加する。</documentation>
            </annotation></attribute>
    </complexType>

    <complexType name="ConfigFile">
        <annotation>
            <documentation>プロパティファイルの読み込みを設定する際に利用する型。</documentation>
        </annotation>
        <attribute name="file" type="string" use="required">
            <annotation>
                <documentation>読み込みを行うプロパティファイルのファイル名を設定する。
コンテナはこの属性に記述されたプロパティファイルをの読み込みを行う。

属性dirを指定した場合、この属性にはワイルドカードを使用できる。
例えば"*.properties"を指定した場合、属性dirに指定したディレクトリ直下の拡張子"properties"のファイルが全てプロパティファイルとして読み込まれる。</documentation>
            </annotation></attribute>
        <attribute name="encoding" type="string">
            <annotation>
                <documentation>プロパティファイルの文字コードを指定する。
コンテナはこの指定に従いプロパティファイルをロードする。</documentation>
            </annotation></attribute>
        <attribute name="dir" type="string">
            <annotation>
                <documentation>プロパティファイルを配置するディレクトリを設定する。
コンテナはこの属性に記述されたディレクトリ以下にあるプロパティファイルを読み込む。
</documentation>
            </annotation></attribute>
    </complexType>

    <complexType name="Import">
        <annotation>
            <documentation>コンポーネントのインポート設定に利用する型。</documentation>
        </annotation>
        <attribute name="file" type="string" use="required">
            <annotation>
                <documentation>インポートする設定ファイルのファイル名を設定する。
コンテナはこの属性に記述された設定ファイルの読み込みを行う。

属性dirを指定した場合、この属性にはワイルドカードを使用できる。
例えば"*.xml"を指定した場合、属性dirに指定したディレクトリ直下の拡張子"xml"のファイルが全て設定ファイルとして読み込まれる。</documentation>
            </annotation></attribute>
        <attribute name="dir" type="string">
            <annotation>
                <documentation>インポートするファイルのディレクトリを設定する。
コンテナはこの属性に記述されたディレクトリ以下にある設定ファイルを読み込む。
</documentation>
            </annotation></attribute>
    </complexType>

    <simpleType name="AutowireType">
        <annotation>
            <documentation>自動インジェクションの種類を意味する型。

ByType: 型による自動インジェクションを行う。
ByName: 名前による自動インジェクションを行う。
None: 自動インジェクションを行わない。</documentation>
        </annotation>
        <restriction base="string">
            <enumeration value="ByType"></enumeration>
            <enumeration value="ByName"></enumeration>
            <enumeration value="None"></enumeration>
        </restriction>
    </simpleType>


    <complexType name="ComponentRef">
        <attribute name="name" type="string">
            <annotation>
                <documentation>コンポーネントの名称を設定する。
コンテナはこの属性で設定した名称でこのコンポーネントを参照する。


</documentation>
            </annotation></attribute>
    </complexType>
</schema>

=== nablarch/nablarch-biz-sample-all/nablarch-messaging-simulator/src/main/resources/outgoing-http-simulator-component-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ==========================================================================
  メッセージ送信シミュレータの設定。

  シミュレータは都度起動バッチとして起動する。
=========================================================================== -->
<component-configuration
    xmlns="http://tis.co.jp/nablarch/component-configuration"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration  ./component-configuration.xsd">

  <config-file file="outgoing-simulator.config" />
  <config-file file="outgoing/messageSenderSettings.config" />

  <!-- テストデータ解析クラス -->
  <import file="dataParser.xml"/>


  <!-- デフォルト設定で使用するSyncMessageConvertorのコンポーネント定義 -->
  <component name="defaultSyncMessageConvertor" class="nablarch.fw.messaging.SyncMessageConvertor" />

  <!-- 日付関連設定（ログ出力などに必要） -->
  <import file="common/date.xml" />

  <!-- スレッド制御用ハンドラ -->
  <component name="multiThreadExecutionHandler" class="nablarch.fw.handler.MultiThreadExecutionHandler">
    <property name="concurrentNumber" value="${threadCount}" />
  </component>

  <!-- ハンドラーキュー構成 -->
  <list name="handlerQueue">

    <!-- ステータスコード変換ハンドラ -->
    <component class="nablarch.fw.handler.StatusCodeConvertHandler" />

    <!-- グローバルエラーハンドラ (メインスレッド用) -->
    <component class="nablarch.fw.handler.GlobalErrorHandler" />

    <!-- リクエストパスベースディスパッチハンドラ -->
    <component class="nablarch.fw.handler.RequestPathJavaPackageMapping">
      <property name="basePackage" value="please.change.me.simulator.outgoing.action.OutgoingSimulatorAction" />
      <property name="immediate" value="false" />
    </component>

    <!-- スレッド実行ハンドラ -->
    <component-ref name="multiThreadExecutionHandler" />


    <!-- リクエストスレッドループハンドラ -->
    <component class="nablarch.fw.handler.RequestThreadLoopHandler" />

    <!-- データリードハンドラ -->
    <component class="nablarch.fw.handler.DataReadHandler" />

  </list>

  <!-- HTTP通信用クライアント -->
  <component name="defaultMessageSenderClient" class="nablarch.fw.messaging.realtime.http.client.HttpMessagingClient">
  </component>

  <component name="filePathSetting" class="nablarch.core.util.FilePathSetting">
    <property name="basePathSettings">
      <map>
        <!-- リクエストデータ一覧CSVファイルの格納ディレクトリ -->
        <entry key="input" value="file:${input-file-dir}" />
        <entry key="format" value="file:${format-file-dir}" />
        <entry key="sendSyncTestData" value="file:${input-file-dir}" />
      </map>
    </property>
    <property name="fileExtensions">
      <map>
        <entry key="sendSyncTestData" value="xls" />
        <entry key="format" value="fmt" />
      </map>
    </property>
  </component>



</component-configuration>

=== nablarch/nablarch-biz-sample-all/nablarch-messaging-simulator/src/main/resources/dataParser.xml
<?xml version="1.0" encoding="UTF-8"?>
<component-configuration
        xmlns="http://tis.co.jp/nablarch/component-configuration"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration ./component-configuration.xsd">

  <!-- TestDataParser -->
  <component name="messagingTestDataParser" class="nablarch.test.core.reader.BasicTestDataParser">
    <property name="testDataReader">
      <component name="xlsReaderForPoi" class="nablarch.test.core.reader.PoiXlsReader"/>
    </property>
    <property name="interpreters" ref="messagingTestInterpreters" />
  </component>

  <!-- テストデータ記法の解釈を行うクラス群 -->
  <list name="messagingTestInterpreters">
    <!-- null変換 -->
    <component class="nablarch.test.core.util.interpreter.NullInterpreter"/>
    <!-- 引用符を外す -->
    <component class="nablarch.test.core.util.interpreter.QuotationTrimmer"/>
    <!-- 文字列増幅 -->
    <component class="nablarch.test.core.util.interpreter.CompositeInterpreter">
      <property name="interpreters">
        <list>
          <component class="nablarch.test.core.util.interpreter.BasicJapaneseCharacterInterpreter"/>
        </list>
      </property>
    </component>
  </list>
  
  
</component-configuration>

=== nablarch/nablarch-biz-sample-all/src/test/resources/unit-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<component-configuration xmlns="http://tis.co.jp/nablarch/component-configuration"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration ./component-configuration.xsd">

  <!-- テスト用設定値 -->
  <config-file file="unit-test.config"/>
  <import file="db-default.xml"/>

  <!-- システム日付、業務日付を固定値に設定 -->
  <component name="dateProvider" class="nablarch.test.FixedSystemTimeProvider">
    <property name="fixedDate" value="20100914123456"/>
  </component>

  <!-- dbInfo -->
  <component name="dbInfo" class="nablarch.test.core.db.GenericJdbcDbInfo">
    <property name="dataSource" ref="dataSource"/>
    <property name="schema" value="${db.user}"/>
  </component>

  <!-- TestDataParser -->
  <component name="testDataParser" class="nablarch.test.core.reader.BasicTestDataParser">
    <property name="testDataReader">
      <component name="xlsReaderForPoi" class="nablarch.test.core.reader.PoiXlsReader"/>
    </property>
    <property name="dbInfo" ref="dbInfo"/>
    <property name="interpreters" ref="interpreters"/>
  </component>

    <!-- テストデータ記法の解釈を行うクラス群 -->
    <list name="interpreters">
        <!-- null変換 -->
        <component class="nablarch.test.core.util.interpreter.NullInterpreter" />
        <!-- 引用符を外す -->
        <component
            class="nablarch.test.core.util.interpreter.QuotationTrimmer" />
        <!-- システム時刻記法 -->
        <component
            class="nablarch.test.core.util.interpreter.DateTimeInterpreter">
            <property name="systemTimeProvider" ref="dateProvider" />
        </component>
        <!-- 文字列増幅 -->
        <component
            class="nablarch.test.core.util.interpreter.CompositeInterpreter">
            <property name="interpreters">
                <list>
                    <component
                        class="nablarch.test.core.util.interpreter.BasicJapaneseCharacterInterpreter" />
                </list>
            </property>
        </component>
    </list>

</component-configuration>

=== nablarch/nablarch-biz-sample-all/nablarch-messaging-simulator/src/test/resources/override/date.xml
<?xml version="1.0" encoding="UTF-8"?>
<component-configuration
    xmlns="http://tis.co.jp/nablarch/component-configuration"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration ../component-configuration.xsd">


  <component name="systemTimeProvider"
      class="nablarch.test.FixedSystemTimeProvider">
    <property name="fixedDate" value="20100913123456" />
  </component>


  <component name="businessDateProvider"
      class="nablarch.test.FixedBusinessDateProvider">
    <property name="fixedDate">
      <map>
        <entry key="00" value="20100914" />
      </map>
    </property>
    <property name="defaultSegment" value="00" />
  </component>


</component-configuration>

=== nablarch/nablarch-biz-sample-all/src/test/resources/please/change/me/common/captcha/message.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
メッセージ用設定ファイル
-->
<component-configuration
    xmlns="http://tis.co.jp/nablarch/component-configuration"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration  ../component-configuration.xsd">

  <!-- 文字列リソースのロードモジュール -->
  <component name="stringResourceLoader"
      class="nablarch.core.message.BasicStringResourceLoader">
    <property name="dbManager" ref="defaultDbTransactionManager" />
    <!-- メッセージリソーステーブル名 -->
    <property name="tableName" value="MESSAGE" />
    <!-- メッセージリソーステーブル IDカラム名 -->
    <property name="idColumnName" value="MESSAGE_ID" />
    <!-- メッセージリソーステーブル 言語カラム名 -->
    <property name="langColumnName" value="LANG" />
    <!-- メッセージリソーステーブル メッセージカラム名 -->
    <property name="valueColumnName" value="MESSAGE" />
  </component>

  <!-- 文字列リソースのキャッシュ -->
  <component name="stringResourceCache"
      class="nablarch.core.cache.BasicStaticDataCache">
    <property name="loader" ref="stringResourceLoader" />
    <!-- 初期ロード -->
    <property name="loadOnStartup" value="${loadMessageOnStartUp}" />
  </component>

  <!-- 文字列リソースの保持クラス -->
  <component name="stringResourceHolder"
      class="nablarch.core.message.StringResourceHolder">
    <property name="stringResourceCache" ref="stringResourceCache" />
  </component>
</component-configuration>

=== nablarch/nablarch-biz-sample-all/nablarch-messaging-simulator/src/main/resources/outgoing/messagingProviders.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- メッセージ送信のメッセージングプロバイダ定義 -->
<component-configuration
    xmlns="http://tis.co.jp/nablarch/component-configuration"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration  ../component-configuration.xsd">

  <!-- 設定ファイル -->
  <config-file file="outgoing/messagingProviders.config" />

  <!-- ユニットテスト用の組み込みMOMを使用する設定 -->
  <!-- キュー名設定について -->
  <!-- 
  1. サービス側にある要求受信キューの論理名
  2. 要求受信キュー
  3. 要求電文退避キュー
  4. 応答受信キュー
  5. 応答電文退避キュー
   -->
  <!-- defaultTimeToLiveは、 送信メッセージの有効期間 (テスト用のため消さない。)-->
  <!--  
  <component name="messagingProvider"
             class="nablarch.test.core.messaging.EmbeddedMessagingProvider">
    <property
        name="queueNames">
      <list>
        <value>TEST.REQUEST</value>
        <value>TEST.REQUEST.POISON</value>
        <value>TEST.RESPONSE</value>
        <value>TEST.RESPONSE.POISON</value>
      </list>
    </property>
    <property name="defaultTimeToLive" value="0" />
  </component>
  -->
  <!-- IBM MQを使用するための設定(詳細は、fw_integration_sampleのdocを参照) -->
  <component name="messagingProvider"
      class="nablarch.integration.messaging.wmq.provider.WmqMessagingProvider">
    <property name="useXa" value="${useXA}" />
    <property name="queueManagerName" value="${queueManagerName}" />
    <property name="receivedQueueName" value="${receiveQueueName}" />
    <property name="sendingQueueNames">
      <list>
        <value>${sendQueueName}</value>
      </list>
    </property>
    <property name="poisonQueueName" value="${poisonQueueName}" />
    <property name="backoutLimit" value="${backoutLimit}" />
    <property name="defaultResponseTimeout" value="${readTimeout}" />
    <property name="useProductSystemErrorOutput" value="${useProductSystemErrorOutput}" />
    <property name="defaultTimeToLive" value="${timeToLive}" />
  </component>
</component-configuration>

=== nablarch/nablarch-biz-sample-all/nablarch-formatter-extension/src/test/resources/messaging-sync-receive-boot.xml
<?xml version="1.0" encoding="UTF-8"?>
<component-configuration
    xmlns="http://tis.co.jp/nablarch/component-configuration"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration https://nablarch.github.io/schema/component-configuration.xsd">

  <!-- プロダクション用の設定読み込み -->
  <import file="messaging-sync-receive-component-configuration.xml"/>

  <import file="nablarch/core/date_test.xml"/>

  <!-- マルチスレッド実行制御ハンドラの無効化 -->
  <component name ="multiThreadExecutionHandler" class="nablarch.test.NopHandler" />

  <!-- リクエストスレッド側のループハンドラの無効化 -->
  <component name="requestThreadLoopHandler" class="nablarch.test.NopHandler" />

  <!-- テスト用のフォーマットファクトリ -->
  <component name="formatterFactory" class="nablarch.core.dataformat.FormatterFactory">
    <property name="cacheLayoutFileDefinition" value="false" />
  </component>

  <!-- フレームワーク制御ヘッダー定義(テスト用) -->
  <component name="fwHeaderDefinition"
      class="nablarch.fw.messaging.StandardFwHeaderDefinition">
    <property name="formatFileName" value="header" />
  </component>

  <!-- テスト用メッセージングプロバイダ -->
  <component name="messagingProvider"
      class="nablarch.test.core.messaging.EmbeddedMessagingProvider">
    <!-- キュー定義 -->
    <property name="queueNames">
      <list>
        <!-- サービス側にある要求受信キューの論理名 -->
        <value>TEST.REQUEST</value>
        <value>TEST.RESPONSE</value>
      </list>
    </property>
  </component>

  <!-- 初期化が必要なコンポーネント -->
  <component name="initializer"
             class="nablarch.core.repository.initialization.BasicApplicationInitializer">
    <property name="initializeList">
      <list>
        <!-- batch/handler/processStop.xml:処理停止ハンドラ -->
        <component-ref name="processStopHandler" />
        <!-- メッセージングプロバイダ -->
        <component-ref name="messagingProvider" />
      </list>
    </property>
  </component>

</component-configuration>

=== nablarch/nablarch-biz-sample-all/nablarch-messaging-simulator/src/main/resources/incoming-mom-simulator-component-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ==========================================================================
  MOM同期応答メッセージ受信シミュレータの設定。

  シミュレータは常駐バッチとして起動する。
=========================================================================== -->
<component-configuration
    xmlns="http://tis.co.jp/nablarch/component-configuration"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration  ./component-configuration.xsd">

  <config-file file="incoming-mom-simulator.config" />

  <!-- テストデータ解析クラス -->
  <import file="dataParser.xml"/>

  <!-- MOM同期応答メッセージ受信のメッセージングプロバイダ定義 -->
  <import file="incoming/messagingProviders.xml" />

  <!-- 日付関連設定（ログ出力などに必要） -->
  <import file="common/date.xml" />

  <!-- スレッド制御用ハンドラ -->
  <component name="multiThreadExecutionHandler" class="nablarch.fw.handler.MultiThreadExecutionHandler">
    <property name="concurrentNumber" value="${threadCount}" />
  </component>

  <!-- データリーダ定義 -->
  <component name="dataReader"
             class="nablarch.fw.messaging.reader.MessageReader">
    <property name="receiveQueueName" value="${receiveQueueName}" />
    <property name="readTimeout" value="${readTimeout}" />
  </component>

  <!-- ハンドラーキュー構成 -->
  <list name="handlerQueue">

    <!-- ステータスコード変換ハンドラ -->
    <component class="nablarch.fw.handler.StatusCodeConvertHandler" />

    <!-- グローバルエラーハンドラ (メインスレッド用) -->
    <component class="nablarch.fw.handler.GlobalErrorHandler" />

    <!-- スレッド実行ハンドラ -->
    <component-ref name="multiThreadExecutionHandler" />

    <!-- メッセージコンテキスト管理ハンドラ -->
    <component class="nablarch.fw.messaging.handler.MessagingContextHandler" />

    <!-- リクエストスレッドループハンドラ -->
    <component class="nablarch.fw.handler.RequestThreadLoopHandler" />

    <!-- データリードハンドラ -->
    <component class="nablarch.fw.handler.DataReadHandler" />

    <component class="please.change.me.simulator.incoming.mom.action.MomIncomingSimulateAction" />

  </list>
  <component name="filePathSetting" class="nablarch.core.util.FilePathSetting">
    <property name="basePathSettings">
      <map>
        <!-- レスポンスデータの格納ディレクトリ -->
        <entry key="sendSyncTestData" value="file:${input-file-dir}" />
      </map>
    </property>
    <property name="fileExtensions">
      <map>
        <entry key="sendSyncTestData" value="xls" />
      </map>
    </property>
  </component>
  </component-configuration>
