=== nablarch/nablarch-biz-sample-all/nablarch-messaging-simulator/src/test/resources/component-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://tis.co.jp/nablarch/component-configuration"
    elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://tis.co.jp/nablarch/component-configuration">

    <element name="component-configuration">
        <annotation>
            <documentation>コンポーネント設定のルート要素。</documentation>
        </annotation>
        <complexType>
            <choice maxOccurs="unbounded" minOccurs="1">
                <element name="import" type="tns:Import" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>他の設定ファイルのインポートを設定する。
コンテナは設定に従い再帰的に他の設定ファイルの読み込みを行なう。</documentation>
                    </annotation>
                </element>
                <element name="config-file"
                    type="tns:ConfigFile" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>プロパティファイルの読み込みを設定する。
コンテナは設定に従い再帰的にプロパティファイルの読み込みを行なう。

プロパティファイルに記述された文字列は、XMLファイル内で"${propName}"のように参照できる。</documentation>
                    </annotation>
                </element>
                <element name="component" type="tns:Component" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>コンポーネントを設定する。
コンテナはこの設定に従い、コンポーネントの生成とインジェクションを行いコンテナ内に登録する。</documentation>
                    </annotation>
                </element>
                <element name="list" type="tns:List" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>Listをコンポーネントとして設定する。
コンテナはこの設定に従い、Listインタフェースを実装したインスタンスを生成、構築しコンポーネントとしてコンテナ内に登録する。</documentation>
                    </annotation>
                </element>
                <element name="map" type="tns:Map" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>Mapをコンポーネントとして設定する。
コンテナはこの設定に従い、Mapインタフェースを実装したインスタンスを生成、構築しコンポーネントとしてコンテナ内に登録する。</documentation>
                    </annotation>
                </element>
            </choice>
        </complexType>
    </element>

    <complexType name="Component">
        <annotation>
            <documentation>コンポーネント定義を行う型。</documentation>
        </annotation>
        <sequence>
            <element name="property" type="tns:Property"
                maxOccurs="unbounded" minOccurs="0">
                <annotation>
                    <documentation>コンポーネントのプロパティを設定する。
コンテナはこの要素に設定された値に従い、コンポーネントにプロパティを設定する。</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="name" type="string">
            <annotation>
                <documentation>コンポーネントの名称を設定する。
コンテナはこの属性で設定した名称でこのコンポーネントを登録する。


</documentation>
            </annotation></attribute>
        <attribute name="class" type="string" use="required">
            <annotation>
                <documentation>コンポーネントのクラス名を設定する。
コンテナはこの属性に設定したクラス名を利用してコンポーネントを作成する。
</documentation>
            </annotation></attribute>
        <attribute name="autowireType" type="tns:AutowireType" default="ByType">
            <annotation>
                <documentation>コンポーネントに対して適用する自動インジェクションのタイプを設定する。
コンテナはこの設定を参照して自動インジェクションを行う。

省略した場合、ByTypeを選択した場合と同様の動作となる。</documentation>
            </annotation></attribute>
    </complexType>

    <complexType name="Property">
        <annotation>
            <documentation>コンポーネントにプロパティを設定する際に利用する型。</documentation>
        </annotation>
        <choice >
            <element name="component" type="tns:Component" maxOccurs="1"
                minOccurs="0">
                <annotation>
                    <documentation>プロパティにセットするコンポーネントを設定する。
コンテナはこの要素のコンポーネントを生成し、プロパティにセットする。

この要素にname属性を設定した場合、コンポーネントの名称は上位に位置するコンポーネントの名称の後に「.」を付けてname属性に指定した文字列を結合したものとなる。</documentation>
                </annotation>
            </element>
            <element name="list" type="tns:List" maxOccurs="1"
                minOccurs="0">
                <annotation>
                    <documentation>プロパティにセットするListを設定する。
コンテナはこの要素で定義したListをコンポーネントとして生成し、プロパティにセットする。

この要素にname属性を設定した場合、コンポーネントの名称は上位に位置するコンポーネントの名称の後に「.」を付けてname属性に指定した文字列を結合したものとなる。</documentation>
                </annotation>
            </element>
            <element name="map" type="tns:Map" maxOccurs="1" minOccurs="0">
                <annotation>
                    <documentation>プロパティにセットするMapを設定する。
コンテナはこの要素で定義したMapをコンポーネントとして生成し、プロパティにセットする。

この要素にname属性を設定した場合、コンポーネントの名称は上位に位置するコンポーネントの名称の後に「.」を付けてname属性に指定した文字列を結合したものとなる。</documentation>
                </annotation></element>
        </choice>
        <attribute name="name" type="string" use="required">
            <annotation>
                <documentation>コンポーネントのプロパティ名を設定する。
コンテナはこの設定値に合致するセッタを検索し、プロパティを設定する。</documentation>
            </annotation></attribute>
        <attribute name="value" type="string">
            <annotation>
                <documentation>プロパティにセットする値を設定する。
コンテナはここに設定した文字列を、プロパティの型に併せて変換し、コンポーネントにセットする。

この属性はプロパティの型が下記いずれかの型の場合のみ設定できる。
 * int
 * long
 * boolean
 * java.lang.String
 * java.lang.Integer
 * java.lang.Long
 * java.lang.Boolean
 * java.lang.String[]
</documentation>
            </annotation></attribute>
        <attribute name="ref" type="string">
            <annotation>
                <documentation>プロパティにセットする他のコンポーネントの名称を設定する。
コンテナはこの属性に設定された文字列に合致するコンポーネントをプロパティにセットする。</documentation>
            </annotation></attribute>
    </complexType>


    <complexType name="List">
        <annotation>
            <documentation>Listをコンポーネントとして設定する際に利用する型。</documentation>
        </annotation>
        <choice maxOccurs="unbounded" minOccurs="1">
            <element name="component" type="tns:Component"
                maxOccurs="unbounded" minOccurs="0">
                <annotation>
                    <documentation>
                        Listに含まれるコンポーネントを設定する。
                        コンテナはこの要素に従いコンポーネントを生成し、上位の要素で設定したlistに追加する。
                    </documentation>
                </annotation>
            </element>
            <element name="value" type="string" minOccurs="0"
                maxOccurs="unbounded">
                <annotation>
                    <documentation>
                        Listに含まれる文字列を設定する。
                        コンテナはこの設定に従い、この要素の文字列を上位の要素で設定したlistに追加する。
                    </documentation>
                </annotation>
            </element>
            <element name="component-ref" type="tns:ComponentRef" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>Listに含まれる別定義したコンポーネントを設定する。
コンテナはこの設定に従い、この要素で参照されるコンポーネントをlistに追加する。
                    </documentation>
                </annotation></element>
        </choice>
        <attribute name="name" type="string">
            <annotation>
                <documentation>Listのコンポーネント名を設定する。
コンテナはこの属性で設定した名称でこのListをコンポーネントとして登録する。
</documentation>
            </annotation></attribute>
    </complexType>

    <complexType name="Map">
        <annotation>
            <documentation>Mapをコンポーネントとして設定する際に利用する型。</documentation>
        </annotation>
        <sequence>
            <element name="entry" type="tns:Entry" maxOccurs="unbounded" minOccurs="0">
                <annotation>
                    <documentation>Mapのエントリを設定する。
コンテナはこの要素の設定に従い、Mapにエントリを追加する。</documentation>
                </annotation></element>
        </sequence>
        <attribute name="name" type="string">
            <annotation>
                <documentation>Mpaのコンポーネント名を設定する。
コンテナはこの属性で設定した名称でこのMapをコンポーネントとして登録する。
</documentation>
            </annotation></attribute>
    </complexType>
    
    <complexType name="Entry">
        <annotation>
            <documentation>Mapのエントリを設定する型。</documentation>
        </annotation>
        <sequence>
            <element name="key-component" type="tns:Component"
                maxOccurs="1" minOccurs="0">
                <annotation>
                    <documentation>エントリのキーとなるコンポーネントを設定する。
コンテナはこの要素で設定されたコンポーネントをキーとするエントリを上位の要素で設定したmapに追加する。
</documentation>
                </annotation>
            </element>
            <element name="value-component" type="tns:Component" maxOccurs="1" minOccurs="0">
                <annotation>
                    <documentation>エントリの値となるコンポーネントを設定する。
コンテナはこの要素で設定されたコンポーネントを値とするエントリを上位の要素で設定したmapに追加する。</documentation>
                </annotation></element>
        </sequence>
        <attribute name="key" type="string">
            <annotation>
                <documentation>エントリのキーを設定する。
コンテナはこの属性で設定された文字列をキーとするエントリを上位の要素で設定したmapに追加する。</documentation>
            </annotation></attribute>
        <attribute name="key-name" type="string">
            <annotation>
                <documentation>エントリのキーとなるコンポーネント名を設定する。
コンテナはこの属性で設定された名称に合致するコンポーネントをキーとするエントリを上位の要素で設定したmapに追加する。

</documentation>
            </annotation></attribute>
        <attribute name="value" type="string">
            <annotation>
                <documentation>エントリの値を設定する。
コンテナはこの属性で設定された文字列を値とするエントリを上位の要素で設定したmapに追加する。</documentation>
            </annotation></attribute>
        <attribute name="value-name" type="string">
            <annotation>
                <documentation>エントリの値となるコンポーネントを設定する。
コンテナはこの属性で設定された名称に合致するコンポーネントを値とするエントリを上位の要素で設定したmapに追加する。</documentation>
            </annotation></attribute>
    </complexType>

    <complexType name="ConfigFile">
        <annotation>
            <documentation>プロパティファイルの読み込みを設定する際に利用する型。</documentation>
        </annotation>
        <attribute name="file" type="string" use="required">
            <annotation>
                <documentation>読み込みを行うプロパティファイルのファイル名を設定する。
コンテナはこの属性に記述されたプロパティファイルをの読み込みを行う。

属性dirを指定した場合、この属性にはワイルドカードを使用できる。
例えば"*.properties"を指定した場合、属性dirに指定したディレクトリ直下の拡張子"properties"のファイルが全てプロパティファイルとして読み込まれる。</documentation>
            </annotation></attribute>
        <attribute name="encoding" type="string">
            <annotation>
                <documentation>プロパティファイルの文字コードを指定する。
コンテナはこの指定に従いプロパティファイルをロードする。</documentation>
            </annotation></attribute>
        <attribute name="dir" type="string">
            <annotation>
                <documentation>プロパティファイルを配置するディレクトリを設定する。
コンテナはこの属性に記述されたディレクトリ以下にあるプロパティファイルを読み込む。
</documentation>
            </annotation></attribute>
    </complexType>

    <complexType name="Import">
        <annotation>
            <documentation>コンポーネントのインポート設定に利用する型。</documentation>
        </annotation>
        <attribute name="file" type="string" use="required">
            <annotation>
                <documentation>インポートする設定ファイルのファイル名を設定する。
コンテナはこの属性に記述された設定ファイルの読み込みを行う。

属性dirを指定した場合、この属性にはワイルドカードを使用できる。
例えば"*.xml"を指定した場合、属性dirに指定したディレクトリ直下の拡張子"xml"のファイルが全て設定ファイルとして読み込まれる。</documentation>
            </annotation></attribute>
        <attribute name="dir" type="string">
            <annotation>
                <documentation>インポートするファイルのディレクトリを設定する。
コンテナはこの属性に記述されたディレクトリ以下にある設定ファイルを読み込む。
</documentation>
            </annotation></attribute>
    </complexType>

    <simpleType name="AutowireType">
        <annotation>
            <documentation>自動インジェクションの種類を意味する型。

ByType: 型による自動インジェクションを行う。
ByName: 名前による自動インジェクションを行う。
None: 自動インジェクションを行わない。</documentation>
        </annotation>
        <restriction base="string">
            <enumeration value="ByType"></enumeration>
            <enumeration value="ByName"></enumeration>
            <enumeration value="None"></enumeration>
        </restriction>
    </simpleType>


    <complexType name="ComponentRef">
        <attribute name="name" type="string">
            <annotation>
                <documentation>コンポーネントの名称を設定する。
コンテナはこの属性で設定した名称でこのコンポーネントを参照する。


</documentation>
            </annotation></attribute>
    </complexType>
</schema>

=== nablarch/nablarch-biz-sample-all/src/test/resources/please/change/me/common/file/management/dbFileManagement.xml
<?xml version="1.0" encoding="UTF-8"?>
<component-configuration xmlns="http://tis.co.jp/nablarch/component-configuration"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration https://nablarch.github.io/schema/component-configuration.xsd">

  <!-- ダイアレクト設定 -->
  <!-- 使用するDBに合わせてダイアレクトを設定すること -->
  <component name="dialect" class="nablarch.core.db.dialect.H2Dialect" />

  <component name="transactionFactory" class="nablarch.core.db.transaction.JdbcTransactionFactory" />
  <component class="nablarch.core.db.statement.exception.BasicSqlStatementExceptionFactory" />
  <component name="connectionFactory" class="nablarch.core.db.connection.BasicDbConnectionFactoryForDataSource">
    <property name="dialect" ref="dialect" />
    <property name="dataSource">
      <component class="org.h2.jdbcx.JdbcDataSource">
        <property name="user" value="sa" />
        <property name="password" value="" />
        <property name="URL" value="jdbc:h2:~/nablarch_test" />
      </component>
    </property>
  </component>

  <!-- ファイル管理機能(論理名fileManagementのコンポーネントを、FileManagementUtilクラスが使用する) -->
  <component name="fileManagement" class="please.change.me.common.file.management.DbFileManagement">
    <!-- 格納ファイルの最大長(単位：バイト) -->
    <property name="maxFileSize" value="10000000"/>
    <!-- 採番機能で、DbFileManagement用の採番である旨を識別するためのKey -->
    <property name="fileIdKey" value="1103" />
    <!-- 採番機能 -->
    <property name="idGenerator" ref="mockIdGenerator" />
    <!-- 採番時に使用するフォーマッター -->
    <property name="idFormatter" ref="fileManagementFormatter" />
  </component>

  <!-- 採番機能(ユニットテスト用) -->
  <component name="mockIdGenerator" class="please.change.me.common.file.management.DbFileManagementTest$MockIdGenerator">
  </component>

  <!-- 採番時に使用するフォーマッター(ファイル管理機能から使用) -->
  <component name="fileManagementFormatter" class="nablarch.common.idgenerator.formatter.LpadFormatter">
    <!-- 桁数 -->
    <property name="length" value="18" />
    <!-- 不足している桁を埋める文字 -->
    <property name="paddingChar" value="0" />
  </component>

  <component name="statementFactory" class="nablarch.core.db.statement.BasicStatementFactory">
    <property name="sqlLoader">
      <component name="sqlLoader" class="nablarch.core.db.statement.BasicSqlLoader">
        <property name="fileEncoding" value="utf-8" />
        <property name="extension" value="sql" />
      </component>
    </property>
  </component>

  <component name="dbManager" class="nablarch.core.db.transaction.SimpleDbTransactionManager" >
    <property name="dbTransactionName" value="subTran"/>
    <property name="transactionFactory" ref="transactionFactory" />
    <property name="connectionFactory" ref="connectionFactory" />
  </component>

  <component name="daoContextFactory" class="nablarch.common.dao.BasicDaoContextFactory" />

</component-configuration>

=== nablarch/nablarch-biz-sample-all/nablarch-messaging-simulator/src/main/resources/incoming-http-simulator-component-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ==========================================================================
  HTTPメッセージ受信シミュレータの設定。

  シミュレータは NTFの内蔵サーバ (nablarch.fw.web.HttpServer) を使用して
  HTTPサーバを起動する。
=========================================================================== -->
<component-configuration
    xmlns="http://tis.co.jp/nablarch/component-configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration  ./component-configuration.xsd">

  <!-- テストデータ解析クラス -->
  <import file="dataParser.xml"/>

  <!-- HTTPメッセージ受信シミュレータの設定ファイル -->
  <config-file file="incoming-http-simulator.config" />

  <!-- HTTPメッセージ受信シミュレータのコンポーネント定義 -->
  <component name="server" class="nablarch.fw.web.httpserver.HttpServerJetty12">
    <property name="handlerQueue" ref="handlerQueue" />
    <property name="port" value="${port}" />
    
    <property name="warBasePath" value="${webAppRoot}"/>
  </component>

  <!-- HTTPメッセージ受信シミュレータで使用するハンドラキュー -->
  <list name="handlerQueue">

    <component class="nablarch.fw.handler.GlobalErrorHandler" />

    <!-- HTTP文字エンコーディング制御 -->
    <component class ="nablarch.fw.web.handler.HttpCharacterEncodingHandler">
      <property name="defaultEncoding" value="${defaultEncoding}" />
    </component>

    <!-- HTTPレスポンス出力 -->
    <component class="nablarch.fw.web.handler.HttpResponseHandler" />

    <!-- HTTPアクセスログ出力 -->
    <component class="nablarch.common.web.handler.HttpAccessLogHandler" />

    <!-- マルチパートリクエスト読み込み -->
    <component class="nablarch.fw.web.upload.MultipartHandler">
      <property name="uploadSettings">
        <component class="nablarch.fw.web.upload.UploadSettings">
          <property name="autoCleaning" value="true" />
          <property name="contentLengthLimit" value="1000000" />
        </component>
      </property>
    </component>

    <!-- HTTPメッセージ受信シミュレートアクション -->
    <component class="please.change.me.simulator.incoming.http.action.HttpIncomingSimulateAction" />

  </list>

  <component name="filePathSetting" class="nablarch.core.util.FilePathSetting">
    <property name="basePathSettings">
      <map>
        <!-- アップロードファイルの一時格納場所 -->
        
        <entry key="sendSyncTestData" value="file:${input-file-dir}" />
      </map>
    </property>
    <property name="fileExtensions">
      <map>
        <entry key="sendSyncTestData" value="xls" />
      </map>
    </property>
  </component>
</component-configuration>

=== nablarch/nablarch-biz-sample-all/nablarch-html-mail/src/test/resources/please/change/me/common/mail/html/schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
メール送信に関するテーブルのスキーマ定義ファイル
-->
<component-configuration
    xmlns="http://tis.co.jp/nablarch/component-configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration ../../../../../../Nablarch/resources/component-configuration.xsd">

    <!-- メール送信要求管理テーブルのスキーマ情報 -->
    <component name="mailRequestTable" class="nablarch.common.mail.MailRequestTable">
        <!--メール送信要求管理テーブルの名前 -->
        <property name="tableName" value="MAIL_REQUEST" />
        <!-- メール送信要求管理テーブルの要求IDカラムの名前 -->
        <property name="mailRequestIdColumnName" value="MAIL_REQUEST_ID" />
        <!-- メール送信要求管理テーブルの件名カラムの名前 -->
        <property name="subjectColumnName" value="SUBJECT" />
        <!--メール送信要求管理テーブルの送信者メールアドレスカラムの名前 -->
        <property name="fromColumnName" value="MAIL_FROM" />
        <!--メール送信要求管理テーブルの返信先メールアドレスカラムの名前 -->
        <property name="replyToColumnName" value="REPLY_TO" />
        <!-- メール送信要求管理テーブルの差し戻し先メールアドレスカラムの名前 -->
        <property name="returnPathColumnName" value="RETURN_PATH" />
        <!-- メール送信要求管理テーブルの文字セットカラムの名前 -->
        <property name="charsetColumnName" value="CHARSET" />
        <!-- メール送信要求管理テーブルのステータスカラムの名前 -->
        <property name="statusColumnName" value="STATUS" />
        <!--メール送信要求管理テーブルの要求日時カラムの名前 -->
        <property name="requestDateTimeColumnName" value="REQUEST_DATETIME" />
        <!-- メール送信要求管理テーブルのメール送信日時カラムの名前 -->
        <property name="sendDateTimeColumnName" value="SEND_DATETIME" />
        <!--メール送信要求管理テーブルの本文カラムの名前 -->
        <property name="mailBodyColumnName" value="MAIL_BODY" />
    </component>
    <component name="htmlMailTable" class="please.change.me.common.mail.html.HtmlMailTable" />

    <!-- メール送信先管理テーブルのスキーマ情報 -->
    <component name="mailRecipientTable" class="nablarch.common.mail.MailRecipientTable">
        <!-- メール送信先管理テーブルの名前 -->
        <property name="tableName" value="MAIL_RECIPIENT" />
        <!-- メール送信先管理テーブルの要求管理IDカラムの名前 -->
        <property name="mailRequestIdColumnName" value="MAIL_REQUEST_ID" />
        <!-- メール送信先管理テーブルの連番カラムの名前 -->
        <property name="serialNumberColumnName" value="SERIAL_NUMBER" />
        <!-- メール送信先管理テーブルの送信区分カラムの名前 -->
        <property name="recipientTypeColumnName" value="RECIPIENT_TYPE" />
        <!-- メール送信先管理テーブルのメールアドレスカラムの名前 -->
        <property name="mailAddressColumnName" value="MAIL_ADDRESS" />
    </component>

    <!-- 添付ファイル管理テーブルのスキーマ情報 -->
    <component name="mailAttachedFileTable"
        class="nablarch.common.mail.MailAttachedFileTable">
        <!-- 添付ファイル管理テーブルの名前 -->
        <property name="tableName" value="MAIL_ATTACHED_FILE" />
        <!-- 添付ファイル管理テーブルの要求管理IDカラムの名前 -->
        <property name="mailRequestIdColumnName" value="MAIL_REQUEST_ID" />
        <!-- 添付ファイル管理テーブルの連番カラムの名前 -->
        <property name="serialNumberColumnName" value="SERIAL_NUMBER" />
        <!-- 添付ファイル管理テーブルのファイル名カラムの名前 -->
        <property name="fileNameColumnName" value="FILE_NAME" />
        <!-- 添付ファイル管理テーブルのContent-Typeカラムの名前 -->
        <property name="contentTypeColumnName" value="CONTENT_TYPE" />
        <!-- 添付ファイル管理テーブルの添付ファイルカラムの名前 -->
        <property name="fileColumnName" value="ATTACHED_FILE" />
    </component>

    <!-- メールテンプレート管理テーブルのスキーマ情報 -->
    <component name="mailTemplateTable" class="nablarch.common.mail.MailTemplateTable">
        <!-- メールテンプレート管理テーブルの名前 -->
        <property name="tableName" value="MAIL_TEMPLATE" />
        <!-- メールテンプレート管理テーブルのテンプレートIDカラムの名前 -->
        <property name="mailTemplateIdColumnName" value="MAIL_TEMPLATE_ID" />
        <!-- メールテンプレート管理テーブルの言語カラムの名前 -->
        <property name="langColumnName" value="LANG" />
        <!-- メールテンプレート管理テーブルの件名カラムの名前 -->
        <property name="subjectColumnName" value="SUBJECT" />
        <!-- メールテンプレート管理テーブルの文字セットカラムの名前 -->
        <property name="charsetColumnName" value="CHARSET" />
        <!--メールテンプレート管理テーブルの本文カラムの名前 -->
        <property name="mailBodyColumnName" value="MAIL_BODY" />
    </component>

</component-configuration>

=== nablarch/nablarch-biz-sample-all/nablarch-formatter-extension/src/main/resources/messaging-sync-receive-component-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>

<component-configuration
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://tis.co.jp/nablarch/component-configuration"
    xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration  https://nablarch.github.io/schema/component-configuration.xsd">

  <!-- テーブル定義 -->
  <import file="nablarch/schema-config.xml" />

  <!-- 環境設定ファイル -->
  <config-file file="common.properties" />
  <config-file file="env.properties" />

  <!--
  バッチ固有の設定読み込み
  -->
  <!-- データベース接続・トランザクション設定-->
  <import file="nablarch/batch/db-for-batch.xml" />
  <import file="data-source.xml"/>

  <!-- ファイルパス設定 -->
  <import file="nablarch/batch/filepath-for-batch.xml" />
  <!-- スレッドコンテキスト機能 -->
  <import file="nablarch/batch/threadcontext-for-batch.xml" />
  <!-- 処理停止機能 -->
  <import file="nablarch/common/standalone/process-stop.xml" />
  <!-- プロセス多重起動防止機能 -->
  <import file="nablarch/common/standalone/duplicate-process-check.xml" />
  <!-- コミットログ機能 -->
  <import file="nablarch/common/standalone/commit-log.xml" />
  <!-- マルチスレッド実行制御機能 -->
  <import file="nablarch/common/standalone/multi-thread.xml" />
  <!-- プロセス常駐化機能 -->
  <import file="nablarch/common/standalone/process-service.xml" />
  <!-- リトライ機能 -->
  <import file="nablarch/common/standalone/standalone-retry.xml" />
  <!-- データリード機能 -->
  <import file="nablarch/batch/batch-data-read.xml" />

  <import file="nablarch/core/validation/charset-definition.xml"/>

  <!-- DomainManager 実装クラス設定 -->
  <component name="domainManager" class="please.change.me.domain.ExampleDomainManager"/>

  <!-- メッセージング用コンポーネント定義ここから============================================================================================= -->
  <!-- メッセージ応答制御ハンドラ -->
  <component name="messageReplyHandler" class="nablarch.fw.messaging.handler.MessageReplyHandler" />

  <component name="messagingProvider"
      class="com.nablarch.example.sample.mom.EmbeddedMessagingProvider">
    <property name="url"  value="tcp://localhost:61616" />
    <!-- キュー定義 -->
    <property name="queueNames">
      <list>
        <!-- サービス側にある要求受信キューの論理名 -->
        <value>TEST.REQUEST</value>
        <value>TEST.RESPONSE</value>
      </list>
    </property>
  </component>

  <!-- データリーダ定義 -->
  <component
    name  = "dataReader"
    class = "nablarch.fw.messaging.reader.FwHeaderReader">
    <!-- メッセージリーダ定義 -->
    <property name = "messageReader">
      <component
        class = "nablarch.fw.messaging.reader.MessageReader">
        <!-- 受信監視キューの論理名 -->
        <property
          name  = "receiveQueueName"
          value = "${nablarch.receiveQueueName}"
        />
        <!-- 受信監視タイムアウト時間(msec) -->
        <property
          name  = "readTimeout"
          value = "${nablarch.readTimeout}"
        />
      </component>
    </property>
  </component>
  <!-- メッセージング用コンポーネント定義ここまで============================================================================================= -->

  <!-- ハンドラキュー構成 -->
  <list name="handlerQueue">

    <!-- ステータスコードを終了コードに変換するハンドラ -->
    <component class="nablarch.fw.handler.StatusCodeConvertHandler" />

    <!-- スレッドコンテキスト変数削除ハンドラ -->
    <component class="nablarch.common.handler.threadcontext.ThreadContextClearHandler" />

    <!-- グローバルエラーハンドラ -->
    <component class="nablarch.fw.handler.GlobalErrorHandler" />

    <!-- スレッドコンテキスト設定ハンドラ -->
    <component-ref name="threadContextHandler" />

    <!-- マルチスレッド実行制御ハンドラ -->
    <component-ref name="multiThreadExecutionHandler" />

    <!-- リトライハンドラ -->
    <component-ref name="retryHandler" />

    <!-- メッセージングコンテキストハンドラ -->
    <component class="nablarch.fw.messaging.handler.MessagingContextHandler" />

    <!-- データベース接続管理ハンドラ（業務初期処理・終端処理用） -->
    <component-ref name="dbConnectionManagementHandler" />

    <!-- リクエストスレッドループ -->
    <component-ref name="requestThreadLoopHandler" />

    <!-- 処理停止制御ハンドラ -->
    <component-ref name="processStopHandler" />

    <!-- 電文応答制御ハンドラ -->
    <component-ref name="messageReplyHandler" />

    <!-- データリードハンドラ -->
    <component-ref name="dataReadHandler" />

    <!-- ディスパッチ -->
    <component class="nablarch.fw.handler.RequestPathJavaPackageMapping">
      <property name="basePackage" value="${nablarch.commonProperty.basePackage}" />
      <property name="classNameSuffix" value="Action" />
      <property name="immediate" value="false" />
    </component>

    <!-- トランザクション制御ハンドラ -->
    <component-ref name="transactionManagementHandler" />

  </list>

  <!-- 初期化が必要なコンポーネント -->
  <component name="initializer"
             class="nablarch.core.repository.initialization.BasicApplicationInitializer">
    <property name="initializeList">
      <list>
        <!-- common/date.xml:業務日付コンポーネント -->
        <component-ref name="businessDateProvider" />
        <!-- batch/handler/processStop.xml:処理停止ハンドラ -->
        <component-ref name="processStopHandler" />
        <!-- メッセージングプロバイダ -->
        <component-ref name="messagingProvider" />
      </list>
    </property>
  </component>
</component-configuration>
