=== nablarch/nablarch-biz-sample-all/nablarch-messaging-simulator/src/test/resources/component-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://tis.co.jp/nablarch/component-configuration"
    elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://tis.co.jp/nablarch/component-configuration">

    <element name="component-configuration">
        <annotation>
            <documentation>コンポーネント設定のルート要素。</documentation>
        </annotation>
        <complexType>
            <choice maxOccurs="unbounded" minOccurs="1">
                <element name="import" type="tns:Import" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>他の設定ファイルのインポートを設定する。
コンテナは設定に従い再帰的に他の設定ファイルの読み込みを行なう。</documentation>
                    </annotation>
                </element>
                <element name="config-file"
                    type="tns:ConfigFile" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>プロパティファイルの読み込みを設定する。
コンテナは設定に従い再帰的にプロパティファイルの読み込みを行なう。

プロパティファイルに記述された文字列は、XMLファイル内で"${propName}"のように参照できる。</documentation>
                    </annotation>
                </element>
                <element name="component" type="tns:Component" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>コンポーネントを設定する。
コンテナはこの設定に従い、コンポーネントの生成とインジェクションを行いコンテナ内に登録する。</documentation>
                    </annotation>
                </element>
                <element name="list" type="tns:List" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>Listをコンポーネントとして設定する。
コンテナはこの設定に従い、Listインタフェースを実装したインスタンスを生成、構築しコンポーネントとしてコンテナ内に登録する。</documentation>
                    </annotation>
                </element>
                <element name="map" type="tns:Map" maxOccurs="unbounded" minOccurs="0">
                    <annotation>
                        <documentation>Mapをコンポーネントとして設定する。
コンテナはこの設定に従い、Mapインタフェースを実装したインスタンスを生成、構築しコンポーネントとしてコンテナ内に登録する。</documentation>
                    </annotation>
                </element>
            </choice>
        </complexType>
    </element>

    <complexType name="Component">
        <annotation>
            <documentation>コンポーネント定義を行う型。</documentation>
        </annotation>
        <sequence>
            <element name="property" type="tns:Property"
                maxOccurs="unbounded" minOccurs="0">
                <annotation>
                    <documentation>コンポーネントのプロパティを設定する。
コンテナはこの要素に設定された値に従い、コンポーネントにプロパティを設定する。</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="name" type="string">
            <annotation>
                <documentation>コンポーネントの名称を設定する。
コンテナはこの属性で設定した名称でこのコンポーネントを登録する。


</documentation>
            </annotation></attribute>
        <attribute name="class" type="string" use="required">
            <annotation>
                <documentation>コンポーネントのクラス名を設定する。
コンテナはこの属性に設定したクラス名を利用してコンポーネントを作成する。
</documentation>
            </annotation></attribute>
        <attribute name="autowireType" type="tns:AutowireType" default="ByType">
            <annotation>
                <documentation>コンポーネントに対して適用する自動インジェクションのタイプを設定する。
コンテナはこの設定を参照して自動インジェクションを行う。

省略した場合、ByTypeを選択した場合と同様の動作となる。</documentation>
            </annotation></attribute>
    </complexType>

    <complexType name="Property">
        <annotation>
            <documentation>コンポーネントにプロパティを設定する際に利用する型。</documentation>
        </annotation>
        <choice >
            <element name="component" type="tns:Component" maxOccurs="1"
                minOccurs="0">
                <annotation>
                    <documentation>プロパティにセットするコンポーネントを設定する。
コンテナはこの要素のコンポーネントを生成し、プロパティにセットする。

この要素にname属性を設定した場合、コンポーネントの名称は上位に位置するコンポーネントの名称の後に「.」を付けてname属性に指定した文字列を結合したものとなる。</documentation>
                </annotation>
            </element>
            <element name="list" type="tns:List" maxOccurs="1"
                minOccurs="0">
                <annotation>
                    <documentation>プロパティにセットするListを設定する。
コンテナはこの要素で定義したListをコンポーネントとして生成し、プロパティにセットする。

この要素にname属性を設定した場合、コンポーネントの名称は上位に位置するコンポーネントの名称の後に「.」を付けてname属性に指定した文字列を結合したものとなる。</documentation>
                </annotation>
            </element>
            <element name="map" type="tns:Map" maxOccurs="1" minOccurs="0">
                <annotation>
                    <documentation>プロパティにセットするMapを設定する。
コンテナはこの要素で定義したMapをコンポーネントとして生成し、プロパティにセットする。

この要素にname属性を設定した場合、コンポーネントの名称は上位に位置するコンポーネントの名称の後に「.」を付けてname属性に指定した文字列を結合したものとなる。</documentation>
                </annotation></element>
        </choice>
        <attribute name="name" type="string" use="required">
            <annotation>
                <documentation>コンポーネントのプロパティ名を設定する。
コンテナはこの設定値に合致するセッタを検索し、プロパティを設定する。</documentation>
            </annotation></attribute>
        <attribute name="value" type="string">
            <annotation>
                <documentation>プロパティにセットする値を設定する。
コンテナはここに設定した文字列を、プロパティの型に併せて変換し、コンポーネントにセットする。

この属性はプロパティの型が下記いずれかの型の場合のみ設定できる。
 * int
 * long
 * boolean
 * java.lang.String
 * java.lang.Integer
 * java.lang.Long
 * java.lang.Boolean
 * java.lang.String[]
</documentation>
            </annotation></attribute>
        <attribute name="ref" type="string">
            <annotation>
                <documentation>プロパティにセットする他のコンポーネントの名称を設定する。
コンテナはこの属性に設定された文字列に合致するコンポーネントをプロパティにセットする。</documentation>
            </annotation></attribute>
    </complexType>


    <complexType name="List">
        <annotation>
            <documentation>Listをコンポーネントとして設定する際に利用する型。</documentation>
        </annotation>
        <choice maxOccurs="unbounded" minOccurs="1">
            <element name="component" type="tns:Component"
                maxOccurs="unbounded" minOccurs="0">
                <annotation>
                    <documentation>
                        Listに含まれるコンポーネントを設定する。
                        コンテナはこの要素に従いコンポーネントを生成し、上位の要素で設定したlistに追加する。
                    </documentation>
                </annotation>
            </element>
            <element name="value" type="string" minOccurs="0"
                maxOccurs="unbounded">
                <annotation>
                    <documentation>
                        Listに含まれる文字列を設定する。
                        コンテナはこの設定に従い、この要素の文字列を上位の要素で設定したlistに追加する。
                    </documentation>
                </annotation>
            </element>
            <element name="component-ref" type="tns:ComponentRef" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>Listに含まれる別定義したコンポーネントを設定する。
コンテナはこの設定に従い、この要素で参照されるコンポーネントをlistに追加する。
                    </documentation>
                </annotation></element>
        </choice>
        <attribute name="name" type="string">
            <annotation>
                <documentation>Listのコンポーネント名を設定する。
コンテナはこの属性で設定した名称でこのListをコンポーネントとして登録する。
</documentation>
            </annotation></attribute>
    </complexType>

    <complexType name="Map">
        <annotation>
            <documentation>Mapをコンポーネントとして設定する際に利用する型。</documentation>
        </annotation>
        <sequence>
            <element name="entry" type="tns:Entry" maxOccurs="unbounded" minOccurs="0">
                <annotation>
                    <documentation>Mapのエントリを設定する。
コンテナはこの要素の設定に従い、Mapにエントリを追加する。</documentation>
                </annotation></element>
        </sequence>
        <attribute name="name" type="string">
            <annotation>
                <documentation>Mpaのコンポーネント名を設定する。
コンテナはこの属性で設定した名称でこのMapをコンポーネントとして登録する。
</documentation>
            </annotation></attribute>
    </complexType>
    
    <complexType name="Entry">
        <annotation>
            <documentation>Mapのエントリを設定する型。</documentation>
        </annotation>
        <sequence>
            <element name="key-component" type="tns:Component"
                maxOccurs="1" minOccurs="0">
                <annotation>
                    <documentation>エントリのキーとなるコンポーネントを設定する。
コンテナはこの要素で設定されたコンポーネントをキーとするエントリを上位の要素で設定したmapに追加する。
</documentation>
                </annotation>
            </element>
            <element name="value-component" type="tns:Component" maxOccurs="1" minOccurs="0">
                <annotation>
                    <documentation>エントリの値となるコンポーネントを設定する。
コンテナはこの要素で設定されたコンポーネントを値とするエントリを上位の要素で設定したmapに追加する。</documentation>
                </annotation></element>
        </sequence>
        <attribute name="key" type="string">
            <annotation>
                <documentation>エントリのキーを設定する。
コンテナはこの属性で設定された文字列をキーとするエントリを上位の要素で設定したmapに追加する。</documentation>
            </annotation></attribute>
        <attribute name="key-name" type="string">
            <annotation>
                <documentation>エントリのキーとなるコンポーネント名を設定する。
コンテナはこの属性で設定された名称に合致するコンポーネントをキーとするエントリを上位の要素で設定したmapに追加する。

</documentation>
            </annotation></attribute>
        <attribute name="value" type="string">
            <annotation>
                <documentation>エントリの値を設定する。
コンテナはこの属性で設定された文字列を値とするエントリを上位の要素で設定したmapに追加する。</documentation>
            </annotation></attribute>
        <attribute name="value-name" type="string">
            <annotation>
                <documentation>エントリの値となるコンポーネントを設定する。
コンテナはこの属性で設定された名称に合致するコンポーネントを値とするエントリを上位の要素で設定したmapに追加する。</documentation>
            </annotation></attribute>
    </complexType>

    <complexType name="ConfigFile">
        <annotation>
            <documentation>プロパティファイルの読み込みを設定する際に利用する型。</documentation>
        </annotation>
        <attribute name="file" type="string" use="required">
            <annotation>
                <documentation>読み込みを行うプロパティファイルのファイル名を設定する。
コンテナはこの属性に記述されたプロパティファイルをの読み込みを行う。

属性dirを指定した場合、この属性にはワイルドカードを使用できる。
例えば"*.properties"を指定した場合、属性dirに指定したディレクトリ直下の拡張子"properties"のファイルが全てプロパティファイルとして読み込まれる。</documentation>
            </annotation></attribute>
        <attribute name="encoding" type="string">
            <annotation>
                <documentation>プロパティファイルの文字コードを指定する。
コンテナはこの指定に従いプロパティファイルをロードする。</documentation>
            </annotation></attribute>
        <attribute name="dir" type="string">
            <annotation>
                <documentation>プロパティファイルを配置するディレクトリを設定する。
コンテナはこの属性に記述されたディレクトリ以下にあるプロパティファイルを読み込む。
</documentation>
            </annotation></attribute>
    </complexType>

    <complexType name="Import">
        <annotation>
            <documentation>コンポーネントのインポート設定に利用する型。</documentation>
        </annotation>
        <attribute name="file" type="string" use="required">
            <annotation>
                <documentation>インポートする設定ファイルのファイル名を設定する。
コンテナはこの属性に記述された設定ファイルの読み込みを行う。

属性dirを指定した場合、この属性にはワイルドカードを使用できる。
例えば"*.xml"を指定した場合、属性dirに指定したディレクトリ直下の拡張子"xml"のファイルが全て設定ファイルとして読み込まれる。</documentation>
            </annotation></attribute>
        <attribute name="dir" type="string">
            <annotation>
                <documentation>インポートするファイルのディレクトリを設定する。
コンテナはこの属性に記述されたディレクトリ以下にある設定ファイルを読み込む。
</documentation>
            </annotation></attribute>
    </complexType>

    <simpleType name="AutowireType">
        <annotation>
            <documentation>自動インジェクションの種類を意味する型。

ByType: 型による自動インジェクションを行う。
ByName: 名前による自動インジェクションを行う。
None: 自動インジェクションを行わない。</documentation>
        </annotation>
        <restriction base="string">
            <enumeration value="ByType"></enumeration>
            <enumeration value="ByName"></enumeration>
            <enumeration value="None"></enumeration>
        </restriction>
    </simpleType>


    <complexType name="ComponentRef">
        <attribute name="name" type="string">
            <annotation>
                <documentation>コンポーネントの名称を設定する。
コンテナはこの属性で設定した名称でこのコンポーネントを参照する。


</documentation>
            </annotation></attribute>
    </complexType>
</schema>

=== nablarch/nablarch-biz-sample-all/nablarch-formatter-extension/src/test/resources/unit-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<component-configuration
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://tis.co.jp/nablarch/component-configuration"
        xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration https://nablarch.github.io/schema/component-configuration.xsd">


  <import file="messaging-sync-receive-boot.xml"/>

  <component name="fixedLengthConvertorSetting"
             class="nablarch.core.dataformat.convertor.FixedLengthConvertorSetting">
    <property name="fixedLengthConvertorFactory">
      <component class="please.change.me.core.dataformat.CustomFixedLengthConvertorFactory" />
    </property>
  </component>

  <!-- テストデータコンバータ定義 -->
  <component name="TestDataConverter_FormUrlEncoded"
             class="please.change.me.test.core.file.FormUrlEncodedTestDataConverter"/>

  <!-- 汎用のDB設定 -->
  <component name="dbInfo" class="nablarch.test.core.db.GenericJdbcDbInfo">
    <property name="dataSource" ref="dataSource"/>
    <property name="schema" value="${nablarch.db.schema}"/>
  </component>

  <!-- テスティングフレームワークの設定 -->
  <import file="nablarch/test/test-data.xml"/>
  <import file="nablarch/test/test-transaction.xml"/>

  <!--
  マスタデータ復旧設定
  マスタデータ復旧を使用する際には、いくつかの手順が必要になります。
  設定追加・変更手順を参照して設定してください。
  -->
  <component name="masterDataRestorer"
             class="nablarch.test.core.db.MasterDataRestorer">
    <!-- バックアップスキーマ -->
    <property name="backupSchema" value="PUBLIC"/>
    <!-- 監視対象テーブル一覧 -->
    <property name="tablesTobeWatched">
      <list>
        <value>ID_GENERATE</value>
      </list>
    </property>
  </component>

  <!-- エンティティテスト設定 -->
  <component name="entityTestConfiguration" class="nablarch.test.core.entity.EntityTestConfiguration">
    <property name="maxMessageId" value="{nablarch.core.validation.ee.Length.max.message}"/>
    <property name="maxAndMinMessageId" value="{nablarch.core.validation.ee.Length.min.max.message}"/>
    <property name="fixLengthMessageId" value="{nablarch.core.validation.ee.Length.fixed.message}"/>
    <property name="underLimitMessageId" value="{nablarch.core.validation.ee.Length.min.max.message}"/>
    <property name="minMessageId" value="{nablarch.core.validation.ee.Length.min.message}"/>
    <property name="emptyInputMessageId" value="{nablarch.core.validation.ee.Required.message}"/>
    <property name="characterGenerator">
      <component name="characterGenerator"
                 class="nablarch.test.core.util.generator.BasicJapaneseCharacterGenerator"/>
    </property>
    <property name="validationTestStrategy">
      <component class="nablarch.test.core.entity.BeanValidationTestStrategy"/>
    </property>
  </component>
</component-configuration>

=== nablarch/nablarch-biz-sample-all/test/resources/please/change/me/common/file/management/dbFileManagement.xml
<?xml version="1.0" encoding="UTF-8"?>
<component-configuration xmlns="http://tis.co.jp/nablarch/component-configuration"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration ../../../../../../Nablarch/resources/component-configuration.xsd">

  <config-file file="db.config" />
  <import file="db-default.xml" />

  <component name="sqlLoader" class="nablarch.core.db.statement.BasicSqlLoader">
    <property name="fileEncoding" value="utf-8"/>
    <property name="extension" value="sql"/>
  </component>

  <component name="dbExceptionFactory" class="nablarch.core.db.statement.exception.BasicSqlStatementExceptionFactory">
  </component>

  <!-- フィールド情報ローダーの設定 -->
  <component name="fieldAnnotationCache" class="nablarch.core.cache.BasicStaticDataCache">
    <property name="loader">
      <component class="nablarch.core.db.statement.autoproperty.FieldAndAnnotationLoader"/>
    </property>
    <property name="loadOnStartup" value="false"/>
  </component>

  <!-- 採番機能(ユニットテスト用) -->
  <component name="mockIdGenerator" class="please.change.me.common.file.management.DbFileManagementTest$MockIdGenerator">
  </component>
  
  <!-- ファイル管理機能(論理名fileManagementのコンポーネントを、FileManagementUtilクラスが使用する) -->
  <component name="fileManagement" class="please.change.me.common.file.management.DbFileManagement">
    <!-- 格納ファイルの最大長(単位：バイト) -->
    <property name="maxFileSize" value="10000000"/>
    <!-- 採番機能で、DbFileManagement用の採番である旨を識別するためのKey -->
    <property name="fileIdKey" value="1103" />
    <!-- 採番機能 -->
    <property name="idGenerator" ref="mockIdGenerator" />
    <!-- 採番時に使用するフォーマッター -->
    <property name="idFormatter" ref="fileManagementFormatter" />
  </component>

  <!-- 採番時に使用するフォーマッター(ファイル管理機能から使用) -->
  <component name="fileManagementFormatter" class="nablarch.common.idgenerator.formatter.LpadFormatter">
    <!-- 桁数 -->
    <property name="length" value="18" />
    <!-- 不足している桁を埋める文字 -->
    <property name="paddingChar" value="0" />
  </component>
</component-configuration>

=== nablarch/nablarch-biz-sample-all/test/resources/unit-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<component-configuration xmlns="http://tis.co.jp/nablarch/component-configuration"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration ./component-configuration.xsd">

  <!-- テスト用設定値 -->
  <config-file file="unit-test.config"/>
  <config-file file="db.config"/>
  <import file="db-default.xml"/>

  <!-- システム日付、業務日付を固定値に設定 -->
  <component name="dateProvider" class="nablarch.test.FixedSystemTimeProvider">
    <property name="fixedDate" value="20100914123456"/>
  </component>
  
  <component name="sqlLoader" class="nablarch.core.db.statement.BasicSqlLoader">
    <property name="fileEncoding" value="utf-8"/>
    <property name="extension" value="sql"/>
  </component>

  <component name="dbExceptionFactory" class="nablarch.core.db.statement.exception.BasicSqlStatementExceptionFactory">
  </component>

  <!-- フィールド情報ローダーの設定 -->
  <component name="fieldAnnotationCache" class="nablarch.core.cache.BasicStaticDataCache">
    <property name="loader">
      <component class="nablarch.core.db.statement.autoproperty.FieldAndAnnotationLoader"/>
    </property>
    <property name="loadOnStartup" value="false"/>
  </component>
  
  <!-- dbInfo -->
  <component name="dbInfo" class="nablarch.test.core.db.GenericJdbcDbInfo">
    <property name="dataSource" ref="dataSource"/>
    <property name="schema" value="${db.user}"/>
  </component>

  <!-- テスト用DbManagerの設定 -->
  <component name="dbManager" class="nablarch.core.db.transaction.SimpleDbTransactionManager"/>
  <component name="testFwTran" class="nablarch.core.db.transaction.SimpleDbTransactionManager">
    <property name="dbTransactionName" value="test-fw"/>
  </component>

  <component name="testTran" class="nablarch.core.db.transaction.SimpleDbTransactionManager">
    <property name="dbTransactionName" value="test"/>
  </component>

  <!-- TestDataParser -->
  <component name="testDataParser" class="nablarch.test.core.reader.BasicTestDataParser">
    <property name="testDataReader">
      <component name="xlsReaderForPoi" class="nablarch.test.core.reader.PoiXlsReader"/>
    </property>
    <property name="dbInfo" ref="dbInfo"/>
    <property name="interpreters" ref="interpreters"/>
  </component>

    <!-- テストデータ記法の解釈を行うクラス群 -->
    <list name="interpreters">
        <!-- null変換 -->
        <component class="nablarch.test.core.util.interpreter.NullInterpreter" />
        <!-- 引用符を外す -->
        <component
            class="nablarch.test.core.util.interpreter.QuotationTrimmer" />
        <!-- システム時刻記法 -->
        <component
            class="nablarch.test.core.util.interpreter.DateTimeInterpreter">
            <property name="systemTimeProvider" ref="dateProvider" />
        </component>
        <!-- 文字列増幅 -->
        <component
            class="nablarch.test.core.util.interpreter.CompositeInterpreter">
            <property name="interpreters">
                <list>
                    <component
                        class="nablarch.test.core.util.interpreter.BasicJapaneseCharacterInterpreter" />
                </list>
            </property>
        </component>
    </list>

</component-configuration>

=== nablarch/nablarch-biz-sample-all/nablarch-logbook/src/env/dev/resources/handler_dev.xml
<?xml version="1.0" encoding="UTF-8"?>

<component-configuration
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://tis.co.jp/nablarch/component-configuration"
    xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration  https://nablarch.github.io/schema/component-configuration.xsd">

  <!-- ハンドラキュー構成 -->
  <component name="webFrontController" class="nablarch.fw.web.servlet.WebFrontController">
    <property name="handlerQueue">
      <list>
        <component class="nablarch.fw.web.handler.HttpCharacterEncodingHandler"/>

        <component class="nablarch.common.handler.threadcontext.ThreadContextClearHandler"/>

        <component class="nablarch.fw.handler.GlobalErrorHandler"/>


        <component class="nablarch.fw.jaxrs.JaxRsResponseHandler" >
          <property name="responseFinishers">
            <list>
              <component class="nablarch.fw.jaxrs.AdoptHandlerResponseFinisher">
                <property name="handler">
                  <component class="nablarch.fw.web.handler.SecureHandler">
                    <property name="secureResponseHeaderList">
                      <list>
                        <component class="nablarch.fw.web.handler.secure.ContentTypeOptionsHeader" />
                        <component class="nablarch.fw.web.handler.secure.ReferrerPolicyHeader" />
                        <component class="nablarch.fw.web.handler.secure.CacheControlHeader" />
                      </list>
                    </property>
                  </component>
                </property>
              </component>
            </list>
          </property>
        </component>

        <component-ref name="threadContextHandler"/>

        <component class="nablarch.fw.jaxrs.JaxRsAccessLogHandler"/>

        <component-ref name="dbConnectionManagementHandler"/>

        <component-ref name="transactionManagementHandler"/>

        <!-- ホットデプロイハンドラ -->
        <!--　TODO:開発環境で本ハンドラを使用する場合、各PJでホットデプロイ対象となるパッケージを指定すること
        <component class="nablarch.fw.hotdeploy.HotDeployHandler">
          <property name="targetPackages">
            <list>
              <value>com.nablarch.example.app.web.action</value>
              <value>com.nablarch.example.app.web.form</value>
              <value>com.nablarch.example.app.web.core.validation.validator</value>
              <value>com.nablarch.example.app.web.util</value>
            </list>
          </property>
        </component>
        -->

        <component-ref name="packageMapping"/>
      </list>
    </property>
  </component>
</component-configuration>

=== nablarch/nablarch-biz-sample-all/src/test/resources/please/change/me/common/mail/html/handler/processStop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
プロセス停止ハンドラの設定ファイル
-->
<component-configuration
    xmlns="http://tis.co.jp/nablarch/component-configuration"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration ../../component-configuration.xsd">


  <component name="processStopHandler" class="nablarch.fw.handler.BasicProcessStopHandler">
    <property name="checkInterval" value="10" />
    <property name="dbTransactionManager">
      <component
          class="nablarch.core.db.transaction.SimpleDbTransactionManager">
        <property name="dbTransactionName" value="ProcessStopHandler" />
        <!-- トランザクションファクトリ -->
        <property name="transactionFactory" ref="jdbcTransactionFactory" />
        <!-- コネクションファクトリ -->
        <property name="connectionFactory" ref="connectionFactory" />
      </component>
    </property>
    <property name="tableName" value="${requestTable}" />
    <property name="requestIdColumnName" value="${requestIdColumnName}" />
    <property name="processHaltColumnName" value="PROCESS_HALT_FLG" />
    <property name="exitCode" value="50" />
  </component>

</component-configuration>

=== nablarch/nablarch-biz-sample-all/nablarch-html-mail/src/test/resources/please/change/me/common/mail/html/common.xml
<?xml version="1.0" encoding="UTF-8"?>
<component-configuration
    xmlns="http://tis.co.jp/nablarch/component-configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration ../../../../../../Nablarch/resources/component-configuration.xsd">

    <!-- メール送信要求IDジェネレータ -->
    <component name="mailRequestIdGenerator"
        class="nablarch.common.idgenerator.TableIdGenerator">
        <property name="tableName" value="ID_GENERATE_MAIL" />
        <property name="idColumnName" value="ID" />
        <property name="noColumnName" value="NO" />
    </component>

    <!-- メール設定 -->
    <component name="mailRequestConfig" class="nablarch.common.mail.MailRequestConfig">
        <!-- デフォルトの返信先メールアドレス -->
        <property name="defaultReplyTo" value="default.reply.to@please.change.me" />
        <!-- デフォルトの差し戻し先メールアドレス -->
        <property name="defaultReturnPath" value="default.return.path@please.change.me" />
        <!-- デフォルトの文字セット -->
        <property name="defaultCharset" value="ISO-2022-JP" />
        <!-- 最大宛先数 -->
        <property name="maxRecipientCount" value="50" />
        <!-- 最大添付ファイルサイズ -->
        <property name="maxAttachedFileSize" value="1048576" />
    </component>

    <!-- 出力ライブラリ(メール送信)のコード値 -->
    <component name="mailConfig" class="nablarch.common.mail.MailConfig">
        <property name="mailRequestSbnId" value="99" />
        <property name="recipientTypeTO" value="0" />
        <property name="recipientTypeCC" value="1" />
        <property name="recipientTypeBCC" value="2" />
        <property name="statusUnsent" value="0" />
        <property name="statusSent" value="1" />
        <property name="statusFailure" value="2" />
        <property name="sendSuccessMessageId" value="SEND_OK000" />
        <property name="sendFailureCode" value="SEND_FAIL0" />
        <property name="mailRequestCountMessageId" value="REQ_COUNT0" />
        <property name="abnormalEndExitCode" value="199" />
    </component>

</component-configuration>

=== nablarch/nablarch-biz-sample-all/src/test/resources/please/change/me/common/authentication/authentication-db.xml
<?xml version="1.0" encoding="UTF-8"?>
<component-configuration xmlns="http://tis.co.jp/nablarch/component-configuration"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://tis.co.jp/nablarch/component-configuration https://nablarch.github.io/schema/component-configuration.xsd">

  <!-- パスワード暗号化モジュールの設定 -->
  <!-- 各PJ固有の設定を読み込む。 -->
  <import file="please/change/me/common/authentication/passwordEncryptor.xml" />

  <!-- 認証設定 -->
  <!-- 各PJ固有の設定を読み込む。 -->
  <import file="please/change/me/common/authentication/authenticator.xml" />

  <!-- ダイアレクト設定 -->
  <!-- 使用するDBに合わせてダイアレクトを設定すること -->
  <component name="dialect" class="nablarch.core.db.dialect.H2Dialect" />

  <component name="transactionFactory" class="nablarch.core.db.transaction.JdbcTransactionFactory" />
  <component class="nablarch.core.db.statement.exception.BasicSqlStatementExceptionFactory" />
  <component name="connectionFactory" class="nablarch.core.db.connection.BasicDbConnectionFactoryForDataSource">
    <property name="dialect" ref="dialect" />
    <property name="dataSource">
      <component class="org.h2.jdbcx.JdbcDataSource">
        <property name="user" value="sa" />
        <property name="password" value="" />
        <property name="URL" value="jdbc:h2:~/nablarch_test" />
      </component>
    </property>
  </component>

  <component name="statementFactory" class="nablarch.core.db.statement.BasicStatementFactory">
    <property name="sqlLoader">
      <component name="sqlLoader" class="nablarch.core.db.statement.BasicSqlLoader">
        <property name="fileEncoding" value="utf-8" />
        <property name="extension" value="sql" />
      </component>
    </property>
  </component>

  <component name="dbManager" class="nablarch.core.db.transaction.SimpleDbTransactionManager" >
    <property name="dbTransactionName" value="subTran"/>
    <property name="transactionFactory" ref="transactionFactory" />
    <property name="connectionFactory" ref="connectionFactory" />
  </component>

  <component name="daoContextFactory" class="nablarch.common.dao.BasicDaoContextFactory" />

</component-configuration>
